version: "3.8"

x-environment-variables: &environment-variables
  - STORAGE_ACCOUNT_SAS_KEY=${STORAGE_ACCOUNT_SAS_KEY}
  - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
  - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}

services:
  ecc:
    container_name: ecc
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: elephantcallscounter
    tty: true
    environment: *environment-variables